# Generated by Django 2.1.5 on 2021-06-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(default='', max_length=111)),
            ],
        ),
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
