# Generated by Django 2.1.5 on 2021-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='status',
            field=models.EmailField(default='', max_length=111),
        ),
    ]
