# Generated by Django 2.1.5 on 2021-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_logintry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintry',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
