# Generated by Django 2.1.5 on 2021-11-12 06:37

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_loginerror'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
            bases=(models.Model, authentication.models.GetDateTime),
        ),
    ]
